In [20]:
import torch
import math

In [21]:
x = torch.empty(3, 4) # allocates memory for tensor; values are the values in memory at time of allocation
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [23]:
# torch.*_like() produces a tensor with the same shape as the input tensor
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [24]:
# torch.tensor() creates a copy of the data

some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [25]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32) # truncates float to int
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[10.8626,  2.1505, 19.6913],
        [ 0.9956,  1.4148,  5.8364]], dtype=torch.float64)
tensor([[10,  2, 19],
        [ 0,  1,  5]], dtype=torch.int32)


In [26]:
# Basic arithmetic

ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [27]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [28]:
# run-time error

a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
# broadcasting

rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7357, 0.0381, 0.2138, 0.5395],
        [0.3686, 0.4007, 0.7220, 0.8217]])
tensor([[1.4715, 0.0762, 0.4276, 1.0791],
        [0.7371, 0.8014, 1.4439, 1.6434]])


(Brad Heintz's explanation)

The rules for broadcasting are:

Each tensor must have at least one dimension - no empty tensors.

Comparing the dimension sizes of the two tensors, going from last to first:

Each dimension must be equal, or

One of the dimensions must be of size 1, or

The dimension does not exist in one of the tensors

In [ ]:
# valid broadcasting

a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]],

        [[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]],

        [[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]],

        [[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]]])
tensor([[[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]],

        [[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]],

        [[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]],

        [[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]]])
tensor([[[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]],

        [[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]],

        [[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]],

        [[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]]])


In [ ]:
# invalid broadcasting

a =     torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first

c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different

d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.3730, 0.2772, 0.2987, 0.4734],
        [0.0476, 0.8904, 0.5951, 0.1461]])
tensor([[1., -0., 1., -0.],
        [-0., -0., -0., 1.]])
tensor([[ 0., -1.,  0., -1.],
        [-1., -1., -1.,  0.]])
tensor([[ 0.3730, -0.2772,  0.2987, -0.4734],
        [-0.0476, -0.5000, -0.5000,  0.1461]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.7191, 0.4067],
        [0.7301, 0.6276]])
tensor([[2.1573, 1.2201],
        [2.1903, 1.8827]])
torch.return_types.svd(
U=tensor([[-0.6501, -0.7598],
        [-0.7598,  0.6501]]),
S=tensor([3.7882, 0.3667]),
V=tensor([[-0.8096, -0.5870],
        [-0.5870,  0.8096]]))


In [ ]:
# Altering tensors in place

# Most binary operations on tensors return a new tensor with the result of the operation. (e.g. c = a * b creates a new tensor occupying a different region of memory)

a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b)) # a changes, b does not
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b)) # b changes
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7357, 0.0381],
        [0.2138, 0.5395]])

After adding:
tensor([[1.7357, 1.0381],
        [1.2138, 1.5395]])
tensor([[1.7357, 1.0381],
        [1.2138, 1.5395]])
tensor([[0.7357, 0.0381],
        [0.2138, 0.5395]])

After multiplying
tensor([[0.5413, 0.0015],
        [0.0457, 0.2911]])
tensor([[0.5413, 0.0015],
        [0.0457, 0.2911]])


(Brad Heintz's explanation)
There is another option for placing the result of a computation in an existing, allocated tensor. Many of the methods and functions we’ve seen so far - including creation methods! - have an out argument that lets you specify a tensor to receive the output. If the out tensor is the correct shape and dtype, this can happen without a new memory allocation:

In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4300, 0.6102],
        [0.8729, 1.2263]])
tensor([[0.2941, 0.3788],
        [0.4567, 0.0649]])


In [ ]:
# Copying tensors

a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [ ]:
# If you want a separate copy, use clone()

a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones


tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [29]:
# If your source tensor has autograd on, the clone will too.
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.6865, 0.3614],
        [0.6493, 0.2633]], requires_grad=True)
tensor([[0.6865, 0.3614],
        [0.6493, 0.2633]], grad_fn=<CloneBackward0>)
tensor([[0.6865, 0.3614],
        [0.6493, 0.2633]])
tensor([[0.6865, 0.3614],
        [0.6493, 0.2633]], requires_grad=True)


In [30]:
# CUDA support
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [31]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


(Brad Heintz's explanation)
You can query the number of GPUs with torch.cuda.device_count(). If you have more than one GPU, you can specify them by index: device='cuda:0', device='cuda:1', etc.

As a coding practice, specifying our devices everywhere with string constants is pretty fragile. In an ideal world, your code would perform robustly whether you’re on CPU or GPU hardware. You can do this by creating a device handle that can be passed to your tensors instead of a string:

In [32]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.4762, 0.0548],
        [0.2024, 0.5731]])


In [33]:
# Moving a tensor from CPU to GPU
y = torch.rand(2, 2)
y = y.to(my_device)

In [34]:
# Changing tensor shapes

a = torch.rand(3, 226, 226)
b = a.unsqueeze(0) # adds a dimension at index 0

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [36]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape) # doesn't do anything because if it did, it'd change the number of elements in the tensor

torch.Size([1, 20])
tensor([[3.6907e-01, 7.1114e-04, 4.4247e-01, 2.2991e-01, 5.2522e-01, 9.4127e-01,
         9.1769e-01, 1.3804e-01, 2.2586e-02, 3.0251e-01, 1.4478e-01, 5.7584e-01,
         8.9923e-01, 2.3469e-01, 1.8992e-01, 4.0671e-01, 1.5190e-01, 1.5065e-01,
         9.5853e-01, 7.7563e-01]])
torch.Size([20])
tensor([3.6907e-01, 7.1114e-04, 4.4247e-01, 2.2991e-01, 5.2522e-01, 9.4127e-01,
        9.1769e-01, 1.3804e-01, 2.2586e-02, 3.0251e-01, 1.4478e-01, 5.7584e-01,
        8.9923e-01, 2.3469e-01, 1.8992e-01, 4.0671e-01, 1.5190e-01, 1.5065e-01,
        9.5853e-01, 7.7563e-01])
torch.Size([2, 2])
torch.Size([2, 2])


In [37]:
# Applying unsqueeze to broadcasting
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.4509, 0.4509],
         [0.2690, 0.2690],
         [0.8381, 0.8381]],

        [[0.4509, 0.4509],
         [0.2690, 0.2690],
         [0.8381, 0.8381]],

        [[0.4509, 0.4509],
         [0.2690, 0.2690],
         [0.8381, 0.8381]],

        [[0.4509, 0.4509],
         [0.2690, 0.2690],
         [0.8381, 0.8381]]])


In [38]:
# In-place versions of squeeze and unsqueeze

batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


(Brad Heintz's explanation)
When it can, reshape() will return a view on the tensor to be changed - that is, a separate tensor object looking at the same underlying region of memory. This is important: That means any change made to the source tensor will be reflected in the view on that tensor, unless you clone() it.

In [40]:
# Changing shapes more radically, retaining the same number of elements
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [42]:
# NumPy Bridge
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.4207, 0.8220, 0.2617],
        [0.1458, 0.7102, 0.2471]])
[[0.42066115 0.82200915 0.2616781 ]
 [0.14582425 0.710195   0.24705058]]


(Brad Heintz's explanation)
It is important to know that these converted objects are using the same underlying memory as their source objects, meaning that changes to one are reflected in the other:

In [43]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.42066115  0.82200915  0.2616781 ]
 [ 0.14582425 17.          0.24705058]]
